service: dummy
app: dummy
name: backend
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-south-1
  memorySize: 128
custom:
  functionsBasePath: ./
functions:
  app:
    handler: bin/less.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-functions-base-path